/**
 * Mentor Hub Feature - TypeScript Contracts
 * 
 * Owner: Lane H (Mentor Hub)
 * Status: Published ✅ v1.0.0
 * Last Updated: 2026-08-28
 */

export type ScheduleDay = 0 | 1 | 2 | 3 | 4 | 5 | 6; // 0 = Sunday

export interface ScheduleRange {
  dayOfWeek: ScheduleDay;
  startTime: string;     // HH:MM format (24h), e.g., "09:00"
  endTime: string;       // HH:MM format (24h), e.g., "17:00"
  isAvailable: boolean;  // Toggle slot availability
}

export interface MentorProfile {
  uuid: string;           // profiles.id (UUID from auth.users)
  name: string;           // Display name from profile
  expertise: string[];    // Array of specializations ['Machine Learning', 'Deep Learning', 'AI Ethics']
  availability: ScheduleRange[];  // Weekly availability slots
  maxSessionsPerWeek: number;      // Hard limit on sessions per week
  rating: number;         // Average rating (1-5), default 0
  totalSessions: number;  // Counter for completed sessions
  bio?: string;           // Optional short bio
  avatarUrl?: string;     // Optional avatar image URL
}

export type BookingStatus = 'pending' | 'confirmed' | 'cancelled' | 'completed';

export interface BookingSession {
  id: string;             // UUID (auto-generated by DB)
  mentorUuid: string;     // references profiles.id (UUID)
  learnerUuid: string;    // references profiles.id (UUID)
  courseId?: number;      // Optional course reference (bigint)
  scheduledAt: Date;      // Timestamp when session occurs
  status: BookingStatus;  // Session lifecycle state
  timezone: string;       // User's timezone, default 'Asia/Jakarta'
  videoCallUrl?: string;  // Populated after confirmation (WebRTC or external service)
  notes?: string;         // Optional notes from learner
  createdAt: Date;        // Record creation timestamp
  updatedAt: Date;        // Last update timestamp
}

export interface Review {
  id: string;             // UUID (auto-generated)
  sessionId: string;      // references mentoring_sessions.id (booking_session UUID)
  reviewerId: string;     // Who wrote the review (usually learner UUID)
  ratedUserUuid: string;  // Who was reviewed (usually mentor UUID)
  rating: number;         // 1-5 stars
  comment?: string;       // Optional feedback text
  isPublic: boolean;      // Whether to show in public mentor profile
  createdAt: Date;
}

export interface MentorFilterParams {
  expertise?: string[];   // Filter by specific expertise areas
  availableFrom?: Date;   // Find mentors available from this date
  availableUntil?: Date;  // Find mentors available until this date
  minRating?: number;     // Minimum average rating
  maxPrice?: number;      // Optional price filter if implemented later
}

// Response types for API endpoints
export interface AvailableSlot {
  sessionId: string;
  mentorUuid: string;
  mentorName: string;
  courseTitle?: string;
  scheduledAt: Date;
  status: BookingStatus;
}

export interface MentorMatchingResult {
  matchedMentors: MentorProfile[];
  availableSlots: AvailableSlot[];
  filtersApplied: Partial<MentorFilterParams>;
}
